POST https://ingress.qt-1.coreinfra.io/aggregation-hub/api/v1/resources
Accept: application/json
X-Client-Id: {{X-Client-Id}}
X-Client-Version: 6.137.0-rc41
X-Account-Id: {{X-Account-Id}}
X-Account-Name: {{X-Account-Name}}
X-Company-Id: {{X-Company-Id}}
X-Company-Name: {{X-Company-Name}}
Authorization: {{Token}}
Content-Type: application/json

{
  "companyNames": [
    "sap-warriors"
  ],
  "options": {
    "geocodedOnly": true,
    "includeInternalPersons": true,
    "includeCrowdPersons": false
  },
  "bookingsFilter": {
    "earliest": "2022-06-18T05:30:00.550Z",
    "latest": "2022-06-24T19:30:00.550Z",
    "activitiesToExclude": [],
    "considerReleasedAsExclusive": true,
    "considerPlannedAsExclusive": true
  },
  "personIds": []
}

###

