POST http://localhost:8000/api/technicians
Accept: application/json
X-Client-Id: {{X-Client-Id}}
X-Client-Version: 6.137.0-rc41
x-cloud-host: qt.dev.coresuite.com
X-Account-Id: {{X-Account-Id}}
X-Account-Name: {{X-Account-Name}}
X-Company-Id: {{X-Company-Id}}
X-Company-Name: {{X-Company-Name}}
X-Request-ID: {{X-Request-Id}}
Authorization: {{Token}}
Content-Type: application/json

{
  "companyNames": [
    "sap-warriors"
  ],
  "options": {
    "geocodedOnly": true,
    "includeInternalPersons": true,
    "includeCrowdPersons": false
  },
  "bookingsFilter": {
    "activitiesToExclude": [],
    "considerReleasedAsExclusive": true,
    "considerPlannedAsExclusive": true
  },
  "personIds": []
}

###

